/*
 * Generated by XDoclet - Do not edit!
 */
package telasi.recutil.ejb.interfaces;

/**
 * Home interface for RecutilService.
 */
public interface RecutilServiceHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/RecutilService";
   public static final String JNDI_NAME="ejb/RecutilService";

   public telasi.recutil.ejb.interfaces.RecutilService create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
