---- charge (correction)
INSERT INTO RECUT.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(690, '2014 correction', '2014 ß.ÃÀÒÉÝáÅÉÓ ÊÏÒÄØÔÉÒÄÁÀ', 4, null, null, 0, 1, 0, 0, 804, 0);
INSERT INTO RECUT.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(691, '2014 discharge', '2014 ß.ÃÀÒÉÝáÅÉÓ ÌÏáÓÍÀ', 4, null, null, 0, 1, 0, 0, 164, 0);
INSERT INTO RECUT.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(692, '2014 corrected', '2014 ß.ÊÏÒÄØÔÉÒÄÁÖËÉ ÃÀÒÉÝáÅÀ', 4, null, null, 0, 1, 0, 0, 164, 0);

---- debt (correction)
INSERT INTO RECUT.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(693, '2014 debt correction', '2014 ß.ÅÀËÉÓ ÊÏÒÄØÔÉÒÄÁÀ', 4, null, null, 0, 1, 0, 0, 236, 0);

---- current act for 2011 (previous year)
INSERT INTO RECUT.BILLOPERATION (ID, NAME, NAME_BS, TYPE_ID, D1, D2, REQ_CYCLE, REQ_READING, REQ_KWH, REQ_GEL, SEQ, DIFF_GROUP_ID)
VALUES (417, 'oper.actcorr.2014', 'ÄÒÈãÄÒÀÃÉ ÀØÔÉ ÌÉÌÃÉÍÀÒÄ ßËÉÓ 1 ÉÅËÉÓÉÃÀÍ', 4, '30-Jun-2011', null, 0, 0, 0, 0, 50113, 0);

---- 
INSERT INTO recut.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID)
VALUES (1004, 'netwrk', 'ØÓÄËÆÄ ÌÉÄÒÈÄÁÉÓ ÃÄÁÄÔÉÓ ÃÀÒÉÝáÅÀ', 4, null, null, 0, 0, 0, 0, 200001, 0);
INSERT INTO recut.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID)
VALUES (1005, 'netwrk', 'ØÓÄËÆÄ ÌÉÄÒÈÄÁÉÓ ÃÄÁÄÔÉÓ ÃÀÒÉÝáÅÀ', 4, null, null, 0, 0, 0, 0, 200001, 0);
INSERT INTO recut.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID)
VALUES (1006, 'netwrk', 'ØÓÄËÆÄ ÌÉÄÒÈÄÁÉÓ ÃÄÁÄÔÉÓ ÃÀÒÉÝáÅÀ', 4, null, null, 0, 0, 0, 0, 200001, 0);
INSERT INTO recut.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID)
VALUES (1007, 'netwrk', 'ØÓÄËÆÄ ÌÉÄÒÈÄÁÉÓ ÃÄÁÄÔÉÓ ÃÀÒÉÝáÅÀ', 4, null, null, 0, 0, 0, 0, 200001, 0);
INSERT INTO recut.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID)
VALUES (1008, 'netwrk', 'ØÓÄËÆÄ ÌÉÄÒÈÄÁÉÓ ÃÄÁÄÔÉÓ ÃÀÒÉÝáÅÀ', 4, null, null, 0, 0, 0, 0, 200001, 0);
INSERT INTO recut.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID)
VALUES (1009, 'netwrk', 'ØÓÄËÆÄ ÌÉÄÒÈÄÁÉÓ ÃÄÁÄÔÉÓ ÃÀÒÉÝáÅÀ', 4, null, null, 0, 0, 0, 0, 200001, 0);
INSERT INTO recut.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID)
VALUES (1010, 'netwrk', 'ØÓÄËÆÄ ÌÉÄÒÈÄÁÉÓ ÃÄÁÄÔÉÓ ÃÀÒÉÝáÅÀ', 4, null, null, 0, 0, 0, 0, 200001, 0);
