SELECT
  C.CUSTKEY           CUSTKEY,
  A.ACCKEY            ACCKEY,
  C.ACCNUMB           ACCNUMB,
  C.CUSTNAME          CUSTNAME,
  A.ACCID             ACCID,
  A.MTNUMB            MTNUMB,
  T.TYPE_ID           TYPE_ID,
  S.STATUS_ID         STATUS_ID,
  S.CYCLE_DATE        CYCLE_DATE,
  S.CURRENT_TARIFF_ID CURRENT_TARIFF_ID 
FROM
  BS.CUSTOMER C, BS.ACCOUNT A,
  BS.TRANS_OWNER_PARAMS T,
  TP_OWNER_SEARCH S
WHERE
  A.CUSTKEY = C.CUSTKEY AND
  S.CUSTOMER_ID = C.CUSTKEY AND
  S.ACCOUNT_ID = A.ACCKEY AND
  T.ACCOUNT_ID = A.ACCKEY AND
  S.CYCLE_DATE = ?