---- charge (correction)
INSERT INTO BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(110, 'sacialuri', 'ÓÏÝÉÀËÖÒÉ ÐÒÏÂÒÀÌÀ', 4, null, null, 0, 0, 0, 0, 100000, 0);
INSERT INTO BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(185, 'sacialuri', 'ÅÀËÉÓ ÊÏÒÄØÝÉÀ ÛÄÈÀÍáÌÄÁÉÓ ÓÀ×ÖÞÅÄËÆÄ', 4, null, null, 0, 0, 0, 0, 100000, 0);
INSERT INTO BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(525, 'soc.baji', 'ÓÀáÄËÌßÉ×Ï ÁÀÑÉÓ ÃÀÊÉÓÒÄÁÀ', 14, null, null, 0, 0, 0, 0, 100000, 0);
INSERT INTO BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(650, 'depozitis koreqtireba', 'ÃÄÐÏÆÉÔÉÓ ÂÀÃÀáÃÉÓ ÊÏÒÄØÔÉÒÄÁÀ', 4, null, null, 0, 0, 0, 0, 100000, 0);