INSERT INTO recut.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID)
VALUES (1002, 'xxx', 'ØÓÄËÆÄ ÌÉÄÒÈÄÁÉÓ ÃÄÁÄÔÉÓ ÃÀÒÉÝáÅÀ', 4, null, null, 0, 0, 0, 0, 200001, 0);
INSERT INTO recut.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID)
VALUES (119, 'xxx', 'ÂÀÃÀáÃÀ ØÓÄËÉÓ ÌÉÄÒÈÄÁÀÆÄ', 4, null, null, 0, 0, 0, 0, 200002, 0);


