INSERT INTO RECUT.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(1012, 'netwrk', '(ÛÉÃÀ ÁÒÖÍÅÀ) ÓÀÀÅÀÍÓÏ ÂÀÃÀáÃÀ', 4, null, null, 0, 1, 0, 0, 200001, 0);
INSERT INTO RECUT.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(1120, 'netwrk', 'ÊÏÌÐÄÓÀÝÉÀ ØÓÄËÉÓ ÌÉÄÒÈÄÁÀÆÄ', 4, null, null, 0, 1, 0, 0, 200001, 0);

INSERT INTO RECUT.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(1000, 'netwrk', 'ØÓÄËÆÄ ÌÉÄÒÈÄÁÉÓ ÐÀÊÄÔÉÓ ÙÉÒÄÁÖËÄÁÀ', 4, null, null, 0, 1, 0, 0, 200001, 0);
INSERT INTO RECUT.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(1001, 'netwrk', 'ØÓÄËÛÉ ÝÅËÄËÄÁÄÁÉÓ ÐÀÊÄÔÉÓ ÙÉÒÄÁÖËÄÁÀ', 4, null, null, 0, 1, 0, 0, 200001, 0);
INSERT INTO RECUT.BILLOPERATION (ID,NAME,NAME_BS,TYPE_ID,D1,D2,REQ_CYCLE,REQ_READING,REQ_KWH,REQ_GEL,SEQ,DIFF_GROUP_ID) VALUES
(1003, 'netwrk', 'ØÓÄËÆÄ ÌÉÄÒÈÄÁÉÓ ÃÄÁÄÔÉÓ ÃÀÒÉÝáÅÉÓ ÊÏÒÄØÔÉÒÄÁÀ', 4, null, null, 0, 1, 0, 0, 200001, 0);