/*
 * Generated by XDoclet - Do not edit!
 */
package telasi.recutil.ejb.interfaces;

/**
 * Remote interface for RecutilService.
 */
public interface RecutilService
   extends javax.ejb.EJBObject
{
   /**
    * Process signle request.
    */
   public telasi.recutil.ejb.Response processEJBRequest( telasi.recutil.ejb.Request request )
      throws telasi.recutil.ejb.RequestException, java.rmi.RemoteException;

   /**
    * Process requests.
    */
   public java.util.List processDatabaseRequests( java.util.List requests )
      throws telasi.recutil.ejb.RequestException, java.rmi.RemoteException;

}
