SELECT
  R.ID,
  R.CUSTOMER_ID,
  C.CUSTNAME,
  C.ACCNUMB,
  R.ACCOUNT_ID,
  AC.ACCID,
  R.ITEM_ID,
  R.ITEM_DATE,
  R.BILLOPERKEY,
  R.IS_CYCLE,
  R.ITEM_NUMBER,
  R.KWH,
  R.GEL,
  R.KWH_E_CORRECTED,
  R.ECORR_FROM,
  R.PREV_CHARGE_DATE,
  R.BASE_TARIFF_ID
FROM
  RECUT.TP_OWNER_RECALC R,
  BS.CUSTOMER C, BS.ACCOUNT AC
WHERE
  AC.CUSTKEY = C.CUSTKEY AND
  R.ACCOUNT_ID = AC.ACCKEY AND
  R.CYCLE_DATE = ? AND
  R.PRODUCER_CUSTOMER_ID = ? AND
  R.PRODUCER_ACCOUNT_ID = ?
ORDER BY
  R.ITEM_ID

